### ISSUE TITLE
底下那一栏是什么

### ISSUE THREAD

**Issue by f4cker** [sues-lee/SuesNews#1]
底下那一栏是什么?

**Comment by sues-lee** [comment]
请问是5.0系统吗，现在对5.0系统有一些bug，很快就会修复。

**Comment by f4cker** [comment]
现在是4.4的 MIUI6,没开虚拟按键然后底下那一栏显示的就是一条纯(主题)色的条
![screenshot_2015-03-14-10-20-49](https://cloud.githubusercontent.com/assets/3525337/6649930/612ab200-ca34-11e4-9a50-2056fbd27b22.png)

**Comment by sues-lee** [comment]
这应该是因为逻辑没检测出存在物理按键，我再去修改一下相关逻辑，谢谢提醒。

**Comment by f4cker** [comment]
希望越来越完善
